"""The Art of Guessing."""

__author__ = "730400384"

points: int = 0
lives: int
player: str = ""
EMOJI_SMILE = "\U0001F601"


def main() -> None:
    greet()
    global points
    global player
    print("So the objective of the game is pretty simple: you will try to guess random numbers that are generated by me and"
          " accumulate the most amount of points possible. You only have three lives so you have to be careful!"
          " You will earn a point for every correct number that you guess. If you happen to guess incorrectly, you will lose a life,"
          " but your points will not be affected. This game has an easy mode, but there also exists a hard mode.")
    selection = int(input("Are you still up for the challenge? If so, which mode would you like: easy or hard? Enter 1 for easy mode"
                          " or 2 for hard mode. If you don't want to continue playing the game, just enter 0. "))
    if selection == 0:
        print(f"That's okay! It was still a pleasure to meet you, {player}! Maybe you could play some other time!{EMOJI_SMILE}"
              " The total number of points you earned is 0.")
    else:
        while selection > 0:
            if selection == 1:
                selection_easy()
            else:
                points = selection_hard(points)
            selection = int(input("Do you wish to continue the game? If yes, enter 1 for easy mode or 2 for hard mode. If not,"
                                  " just enter 0. "))
        print(f"Thanks for playing the game! Your total number of points of collected is {points}.")


def greet() -> None:
    print("Hello there random stranger! Welcome to the game, \"The Art of Guessing!\" You are at a carnival and the goal of this game is"
          " to see if you really know the strategy behind guessing.")
    print("Before starting, I'd like to get to know you a bit better.")
    global player
    player = str(input("What is your name? "))
    print(f"It is so cool to meet you, {player}!{EMOJI_SMILE}"
          " My name is Smart Computer."
          " Let's begin the game, shall we?")


def selection_easy() -> None:
    global points
    global lives
    lives = 3
    global player
    print(f"Here we go, {player}! You chose the easy mode so you have to pick the random number that I generated between 1 and 2.")
    while lives > 0:
        number_easy = int(input("Which number have I randomly generated? "))
        from random import randint
        random_x_generated = int(randint(1, 2))
        if number_easy == random_x_generated:
            points = points + 1
            print("Great job! You guessed my number! You have earned a point!")
            print("Keep going!")
        else:
            lives = lives - 1
            print(f"Oooooo, sorry. You guessed {number_easy} but my number was actually {random_x_generated}."
                  " You have just lost a life.")
    if points >= 3:
        print(f"Great job, {player}! You got {points} points!")
    else:
        print(f"It is okay that you did not do as well as you have wanted, {player}. You acheived a total count of {points}.")


def selection_hard(value: int) -> int:
    survival: int = 3
    print(f"Here we go, {player}! You chose the hard mode so you have to pick the random number that I generated between 1 and 4.")
    while survival > 0:
        number_hard = int(input("Which number have I randomly generated? "))
        from random import randint
        random_y_generated = int(randint(1, 4))
        if number_hard == random_y_generated:
            value = value + 1
            print("Great job! You guessed my number! You have earned a point!")
            print("Keep going!")
        else:
            survival = survival - 1
            print(f"Oooooo, sorry. You guessed {number_hard} but my number was actually {random_y_generated}."
                  " You have just lost a life.")
    if points >= 3:
        print(f"Great job, {player}! You got {value} points!")
    else:
        print(f"It is okay that you did not do as well as you have wanted, {player}. You acheived a total count of {value}.")
    return value


if __name__ == "__main__":
    main()